---
all:
  children:
    linux:
      hosts:
        web01.example.com:
          ansible_host: 10.0.1.10
        web02.example.com:
          ansible_host: 10.0.1.11
        db01.example.com:
          ansible_host: 10.0.2.10
      vars:
        ansible_user: ansible
    windows:
      hosts:
        win01.example.com:
          ansible_host: 10.0.3.10
      vars:
        ansible_user: Administrator
        ansible_connection: winrm
        ansible_winrm_transport: ntlm
        ansible_winrm_server_cert_validation: ignore
