---
all:
  children:
    production:
      children:
        webservers:
          hosts:
            web01.example.com:
              ansible_host: 10.0.1.10
            web02.example.com:
              ansible_host: 10.0.1.11
      vars:
        ansible_user: ansible
        env: production
